"""Generate the self-contained Obsidian snippet with base64-embedded fonts.

Obsidian resolves url() in snippet CSS against the app origin, not the
snippets folder, so file references silently fail. Embedding the woff2
data directly makes the snippet a single portable file.

Usage:  py tools/make_obsidian_snippet.py
"""

import base64
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
WEB = os.path.join(ROOT, 'dist', 'webfonts')
OUT = os.path.join(ROOT, 'obsidian', 'terminal-workbench-mono.css')

STYLES = [
    ('TerminalWorkbenchMono-Regular.woff2', 400, 'normal'),
    ('TerminalWorkbenchMono-Medium.woff2', 500, 'normal'),
    ('TerminalWorkbenchMono-Bold.woff2', 700, 'normal'),
    ('TerminalWorkbenchMono-Italic.woff2', 400, 'italic'),
    ('TerminalWorkbenchMono-MediumItalic.woff2', 500, 'italic'),
    ('TerminalWorkbenchMono-BoldItalic.woff2', 700, 'italic'),
]

HEADER = """\
/* ============================================================
   Terminal Workbench Mono — Obsidian snippet (fully self-contained)
   ------------------------------------------------------------
   All four font styles are EMBEDDED below as base64. No other
   files are needed; this works in synced vaults and on machines
   where the font is not installed.

   Install:
     1. Drop THIS ONE FILE into  <vault>/.obsidian/snippets/
     2. Settings -> Appearance -> CSS snippets -> enable
        "terminal-workbench-mono"

   What it does by default — themes ALL of Obsidian:
     1) CODE       code blocks, inline code, frontmatter
                   + coding ligatures (-> <- => != == <= >=)
     2) NOTES      editor + reading view body text
     3) INTERFACE  menus, sidebars, tabs, settings

   Don't want all of it? Each numbered section at the bottom of
   this file can be commented out independently.
   Generated by tools/make_obsidian_snippet.py — do not hand-edit
   the base64 blocks. License: SIL OFL 1.1.
   ============================================================ */
"""

RULES = """
/* ============================================================
   1) CODE — code blocks, inline code, frontmatter + ligatures
      (comment this section out to leave code fonts alone)
   ============================================================ */
body {
  --font-monospace: "Terminal Workbench Mono", ui-monospace, monospace;
  --font-monospace-theme: "Terminal Workbench Mono", ui-monospace, monospace;
}
.markdown-source-view .cm-inline-code,
.markdown-rendered code,
.markdown-preview-view code,
.markdown-rendered pre,
.markdown-preview-view pre,
.cm-s-obsidian .HyperMD-codeblock,
.markdown-source-view.mod-cm6 .cm-content .HyperMD-codeblock {
  font-family: "Terminal Workbench Mono", ui-monospace, monospace !important;
  font-variant-ligatures: contextual common-ligatures;
  font-feature-settings: "calt" 1, "liga" 1;
}

/* Box-drawing glyphs fill a full terminal cell (1.22em tall), so they only
   tile vertically when the line box is no taller than that. Pin code BLOCKS
   to 1.2 (a hair of overlap) so │ ║ borders connect across rows. Inline code
   is left alone so it doesn't disturb prose line spacing. */
.markdown-rendered pre,
.markdown-preview-view pre,
.cm-s-obsidian .HyperMD-codeblock,
.markdown-source-view.mod-cm6 .cm-content .HyperMD-codeblock {
  line-height: 1.2;
}

/* ============================================================
   2) NOTES — editor + reading view body text
      (comment this section out to keep your reading font)
   ============================================================ */
body {
  --font-text: "Terminal Workbench Mono", ui-monospace, monospace;
  --font-text-theme: "Terminal Workbench Mono", ui-monospace, monospace;
}
.markdown-preview-view,
.markdown-source-view.mod-cm6 .cm-content {
  font-feature-settings: "calt" 1, "liga" 1;
}

/* ============================================================
   3) INTERFACE — menus, sidebars, tabs, settings, buttons
      (comment this section out for a normal UI font)
   ============================================================ */
body {
  --font-interface: "Terminal Workbench Mono", ui-monospace, monospace;
  --font-interface-theme: "Terminal Workbench Mono", ui-monospace, monospace;
}
"""


def main():
    parts = [HEADER]
    for fname, weight, style in STYLES:
        path = os.path.join(WEB, fname)
        b64 = base64.b64encode(open(path, 'rb').read()).decode('ascii')
        parts.append(
            '@font-face {\n'
            '  font-family: "Terminal Workbench Mono";\n'
            f'  src: url(data:font/woff2;base64,{b64}) format("woff2");\n'
            f'  font-weight: {weight};\n'
            f'  font-style: {style};\n'
            '  font-display: swap;\n'
            '}\n'
        )
    parts.append(RULES)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(parts))
    print('wrote', OUT, f'({os.path.getsize(OUT)/1024:.1f} KB)')


if __name__ == '__main__':
    main()
